apiVersion: v2
name: et-cos
home: https://github.com/hmcts/et-ccd-callbacks
version: 0.0.13
description: HMCTS Employment Tribunals CDD Callbacks Service
maintainers:
  - name: HMCTS Employment Tribunals Team
dependencies:
  - name: java
    version: 3.6.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
